### ISSUE TITLE
Notebook tests

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/cirq-superstaq#117] opened 2021-11-09 22:39 UTC
Check to run notebooks to make sure that the notebook code still works.

**Comment by vtomole** [comment] 2022-02-21 22:48
I'm going to take this.

**Comment by vtomole** [comment] 2022-05-16 02:11
Whoever takes this can reference: https://github.com/quantumlib/Cirq/blob/efd3b25e83a6dacde69d7d000b7de19d8671cea8/.github/workflows/ci.yml#L297

**Comment by pgoiporia** [comment] 2022-05-18 20:46
#249

**Comment by stephanielee9** [comment] 2022-11-16 21:53
Duplicate of https://github.com/SupertechLabs/general-superstaq/issues/66

**Closed by stephanielee9** 2022-11-16 21:53 UTC
Labels: area/inbox-zero
